name: 同步到 MS Todo

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Branch Filestorage Action
      uses: moonrailgun/branch-filestorage-action@v1.2.2
      with:
        branch: graphtoken
        path: graphtoken.asc
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./TodoSynchronizer.CLI/TodoSynchronizer.CLI.csproj
    - name: Build
      run: dotnet build ./TodoSynchronizer.CLI/TodoSynchronizer.CLI.csproj --no-restore -c Release
    - name: Run
      run: ./TodoSynchronizer.CLI/bin/Release/net6.0/TodoSynchronizer.CLI -canvastoken ${{ secrets.CANVAS_TOKEN }} -graphtokenfile graphtoken.asc -configfile config.yaml -graphtokenkey ${{ secrets.KEY }}
